### PR TITLE
Fix onPurchaseFailed callback call

### PR DESCRIPTION
**Pull request by ab-rdarts**
Use storeSpecificId instead of internal unity productId during call OnPurchaseFailed

### CODE REVIEW

**Comment by ab-rdarts** [comment]
@googlebot I signed it!

**Comment by thanwah** [comment]
I'm adding @qing451800 to take a look.

**Comment by githubzephyrmobile** [comment]
@Qing451800 not in this case, please look at documentation of PurchaseFailureDescription. It requires store specific id

**Comment by ab-rdarts** [comment]
@Qing451800 On any purchase failure I do not receive callback on IStoreListener, but with this patch it works as expected. Also unity write error about unknown product

**Comment by ab-rdarts** [comment]
https://docs.unity3d.com/2018.1/Documentation/ScriptReference/Purchasing.Extension.PurchaseFailureDescription.html

**Comment by ab-rdarts** [comment]
Here is log of original failed purchase:
```
2020/05/01 22:24:04.421 23117 23333 Error Unity Failed to purchase unknown product {0}: consumable
2020/05/01 22:24:04.421 23117 23333 Error Unity UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
2020/05/01 22:24:04.421 23117 23333 Error Unity UnityEngine.Logger:LogError(String, Object)
2020/05/01 22:24:04.421 23117 23333 Error Unity UnityEngine.Purchasing.PurchasingManager:OnPurchaseFailed(PurchaseFailureDescription)
2020/05/01 22:24:04.421 23117 23333 Error Unity Google.Play.Billing.<>c__DisplayClass39_3:<ParsePurchaseResult>b__2()
2020/05/01 22:24:04.421 23117 23333 Error Unity System.Action:Invoke()
2020/05/01 22:24:04.421 23117 23333 Error Unity Google.Play.Billing.Internal.GooglePlayBillingUtil:Update()
2020/05/01 22:24:04.421 23117 23333 Error Unity  
2020/05/01 22:24:04.421 23117 23333 Error Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020/05/01 22:24:04.421 23117 23333 Error Unity 
```

Here is the log of patched version:

```
2020/05/01 22:17:18.887 5520 5851 Info Unity onPurchaseFailedEvent({0}): consumable
2020/05/01 22:17:18.887 5520 5851 Info Unity UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
2020/05/01 22:17:18.887 5520 5851 Info Unity UnityEngine.Logger:Log(String, Object)
2020/05/01 22:17:18.887 5520 5851 Info Unity UnityEngine.Purchasing.PurchasingManager:OnPurchaseFailed(PurchaseFailureDescription)
2020/05/01 22:17:18.887 5520 5851 Info Unity Google.Play.Billing.<>c__DisplayClass39_3:<ParsePurchaseResult>b__2()
2020/05/01 22:17:18.887 5520 5851 Info Unity System.Action:Invoke()
2020/05/01 22:17:18.887 5520 5851 Info Unity Google.Play.Billing.Internal.GooglePlayBillingUtil:Update()
2020/05/01 22:17:18.887 5520 5851 Info Unity  
2020/05/01 22:17:18.887 5520 5851 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020/05/01 22:17:18.887 5520 5851 Info Unity 
2020/05/01 22:17:18.887 5520 20814 Warn Adjust InstallReferrer not integrated in project (com.android.installreferrer.api.InstallReferrerClient) thrown by (java.lang.ClassNotFoundException)
2020/05/01 22:17:18.896 5520 5851 Info Unity OnPurchaseFailed: FAIL. Product: 'com.zm.test.nonconsumable.product_2.id', PurchaseFailureReason: Unknown
2020/05/01 22:17:18.896 5520 5851 Info Unity UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
2020/05/01 22:17:18.896 5520 5851 Info Unity UnityEngine.Logger:Log(LogType, Object)
2020/05/01 22:17:18.896 5520 5851 Info Unity UnityEngine.Debug:Log(Object)
2020/05/01 22:17:18.896 5520 5851 Info Unity Store:AddLog(String)
2020/05/01 22:17:18.896 5520 5851 Info Unity Store:OnPurchaseFailed(Product, PurchaseFailureReason)
2020/05/01 22:17:18.896 5520 5851 Info Unity UnityEngine.Purchasing.StoreListenerProxy:OnPurchaseFailed(Product, PurchaseFailureReason)
2020/05/01 22:17:18.896 5520 5851 Info Unity UnityEngine.Purchasing.PurchasingManager:OnPurchaseFailed(PurchaseFailureDescription)
```

As you can see only patched version works without unity error and call OnPurchaseFailed(Product, PurchaseFailureReason). Also note that unity cannot find product 'Failed to purchase unknown product'

**Comment by thanwah** [comment]
Fixed in https://github.com/google/play-unity-plugins/commit/d080a196050b569a203c1eb1876fdf293c22df01. For some reason the linkage to this original PR didn't work, so just closing it out.

**Pull request closed without merging**
