### PR TITLE
Remove Logging in AssetPackManager

### PR DESCRIPTION
**Pull request by trapezoid**
Debug.LogFormat is too expensive call, and too noisy.

### CODE REVIEW

**Comment by trapezoid** [comment]
@googlebot I signed it!

**Comment by trapezoid** [comment]
I am using "AssetBundle.LoadFromStream" and a custom stream implementation to load encrypted assets directly from AssetPack.
To do this, I need to use "GetAssetLocation" to get the file path and offset, so every time I load the AssetBundle, a log is output.
This log output causes performance problems and makes it difficult to analyze various problems from other logs.

I would like to know if there is any special purpose for this log output.

**Comment by trapezoid** [comment]
@thanwah

**Comment by thanwah** [comment]
Thank you, this seems like a good change. I need to import it into our internal review system, but should be able to get it merged.

**Pull request closed without merging**
